server:
  port: 8084
spring:
  application:
    name: classify
ribbon:
  eureka:
    enabled: true
feign:
  httpclient:
    connection-timeout: 30000
hystrix:
  metrics:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/
