server:
  port: 8081
spring:
  application:
    name: orders
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/
hystrix:
  metrics:
    enabled: true
feign:
  httpclient:
    connection-timeout: 30000
ribbon:
  eureka:
    enabled: true
