server:
  port: 8087
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: webapp
  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
    check-template-location: true
    suffix=: .html
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/