hf:
  FileUrl: D:/框架/毕业项目/kkFileView-2.2.0/file/NotifyFIle/
server:
  port: 8089
spring:
  application:
    name: notify
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/
hystrix:
  metrics:
    enabled: true
feign:
  httpclient:
    connection-timeout: 30000
ribbon:
  eureka:
    enabled: true
